// Mocks generated by Mockito 5.4.6 from annotations
// in flowery/test/unit/feature/auth/domain/usecase/login_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowery/core/network/api_result.dart' as _i4;
import 'package:flowery/feature/auth/data/model/forget_password/otp_response_model.dart'
    as _i10;
import 'package:flowery/feature/auth/data/model/login/user_response_model.dart'
    as _i5;
import 'package:flowery/feature/auth/data/model/register/register_response_model.dart'
    as _i8;
import 'package:flowery/feature/auth/domain/entity/login_request.dart' as _i6;
import 'package:flowery/feature/auth/domain/entity/register_request.dart'
    as _i9;
import 'package:flowery/feature/auth/domain/repo/auth_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepo extends _i1.Mock implements _i2.AuthRepo {
  MockAuthRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.UserResponseModel>> login(
    _i6.LoginRequest? login,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [login]),
            returnValue: _i3.Future<_i4.ApiResult<_i5.UserResponseModel>>.value(
              _i7.dummyValue<_i4.ApiResult<_i5.UserResponseModel>>(
                this,
                Invocation.method(#login, [login]),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i5.UserResponseModel>>);

  @override
  _i3.Future<_i4.ApiResult<_i8.RegisterResponseModel>> register(
    _i9.RegisterRequest? register,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [register]),
            returnValue:
                _i3.Future<_i4.ApiResult<_i8.RegisterResponseModel>>.value(
                  _i7.dummyValue<_i4.ApiResult<_i8.RegisterResponseModel>>(
                    this,
                    Invocation.method(#register, [register]),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i8.RegisterResponseModel>>);

  @override
  _i3.Future<_i4.ApiResult<_i10.OtpResponseModel>> forgetPassword(
    String? email,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [email]),
            returnValue: _i3.Future<_i4.ApiResult<_i10.OtpResponseModel>>.value(
              _i7.dummyValue<_i4.ApiResult<_i10.OtpResponseModel>>(
                this,
                Invocation.method(#forgetPassword, [email]),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i10.OtpResponseModel>>);
}
