name: Flutter CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8' # must change depend on flutter version
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit tests
        run: flutter test test/unit